version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /Users/stevencoutts/public-html:/etc/nginx/html
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
